### PR TITLE
Fix topic name

### PR DESCRIPTION
**Pull request by at-wat**
Use md5 suffix only for map key.

### CODE REVIEW

**Comment by at-wat** [comment]
@t-asaka @f-fl0 please take a look

**Review by f-fl0 — APPROVED** [review]
LGTM. I assume it caused problem because `name` is not only used as a key for the publishers map. Sorry I missed that last time.

**Comment by f-fl0** [comment]
Any unittest we could add about that fix?

**Comment by at-wat** [comment]
> Any unittest we could add about that fix?

To test this change, rosmaster xmlrpc call should be mocked, but since the rosmaster API is not abstracted in rosgo code, it requires large structural refactoring.

**Review by t-asaka — APPROVED** [review]
👀

**Pull request merged**
